module.exports = {
  darkMode: "class",
  content: [
    "./src/App.js",
    "./src/pages/SignIn.js",
    "./src/pages/Home.js",
    "./src/pages/Profile.js",
    "./src/pages/Loading.js",
    "./src/pages/SinglePost.js",
    "./src/pages/Settings.js",
    "./src/pages/Photo.js",
    "./src/components/auth/SignInEmail.js",
    "./src/components/auth/SignInGoogle.js",
    "./src/components/loaders/Spinner.js",
    "./src/components/forms/NewPost.js",
    "./src/components/forms/NewComment.js",
    "./src/components/forms/SetProfilePicture.js",
    "./src/components/feed/Feed.js",
    "./src/components/PostsList.js",
    "./src/components/header/Header.js",
    "./src/components/post/PostSkeleton.js",
    "./src/components/post/PostAside.js",
    "./src/components/post/PostHeader.js",
    "./src/components/post/PostContent.js",
    "./src/components/post/PostImage.js",
    "./src/components/post/PostFooter.js",
    "./src/components/post/Post.js",
    "./src/components/post/highlightedPost/HighlightedPost.js",
    "./src/components/notifications/Notification.js",
    "./src/components/notifications/CommentNotification.js",
    "./src/components/floatingButton/FloatingButton.js",
    "./src/components/alerts/AlertPositive.js",
    "./src/components/modals/BottomModal.js",
    "./src/components/modals/Modal.js",
    "./src/components/nav/Nav.js",
    "./src/components/nav/MobileNav.js",
    "./src/components/comment/Comments.js",
    "./src/components/profile/ProfileHeader.js",
  ],
  theme: {
    extend: {},
  },
};
